name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.1.1
author: Aleksander WoÅºniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  simple_gesture_detector: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
